project:
  type: website

website:
  title: "OceanStats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blogs.qmd
      - text: Tutorials
        menu: 
          - text: "placeholder 1"
          - text: "placeholder 2"
      - about.qmd

format:
  html:
    #theme: litera
    css: bootstrap.css
    toc: true

editor: visual

