project:
  type: website

website:
  title: "OceanStats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blogs.qmd
      - text: Tutorials
        menu: 
          - text: "placeholder 1"
          - text: "placeholder 2"
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/jessecolephillips/ocean_stats

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true

editor: visual

