project:
  type: website

website:
  title: "OceanStats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blogs.qmd
      - text: Tutorials
        menu: 
          - text: "placeholder 1"
          - text: "placeholder 2"
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/jessecolephillips/ocean_stats
  search: 
    location: navbar
    type: overlay
  announcement: 
    icon: info-circle
    dismissable: true
    content: "This site is a work in progress. Information is still being added on a daily basis."
    type: secondary
    position: below-navbar

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true

editor: visual

